version: "3"

services:
    dice-laravel-dev:
        depends_on:
            dice-db:
              condition: service_healthy
        container_name: dice-laravel-dev
        build:
            context: .
            dockerfile: Dockerfile_backend
        ports:
            - "82:80"
        volumes:
          - ./dice-laravel/:/var/www/html
        command: >
            /bin/sh -c "
            cd /var/www/html/ && 
            chmod u+x entrypoint.sh && 
            ./entrypoint.sh"
        networks:
            - dice-db-network

    dice-react-dev:
        depends_on:
          - dice-laravel
        container_name: dice-react-dev
        build:
            context: .
            dockerfile: DockerfileReact
        environment:
          - DISPLAY=0
          - VITE_APP_API_URL=http://192.168.1.130:82
          - VITE_APP_URL=http://192.168.1.130:4173
          - VITE_APP_PREFIX=
        ports:
            - "83:80"
            - "4173:4173"
            - "5173:5173"
            - "8080:8080" # For random use
            - "9323:9323" # For Playwright Report
            - "63315:63315" # For vitest browser support
        volumes:
            - ./dice-react/:/usr/share/nginx/html
            - ./docker/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            # For playwright e2e testing:
            - /tmp/.X11-unix:/tmp/.X11-unix
        command: >
            bash -c "cd /usr/share/nginx/html/
            && npm install 
            && npm run build
            && npm run preview"

    dice-db:
        container_name: dice-db
        image: mariadb:lts-noble
        environment:
           MYSQL_DATABASE: ${MYSQL_DATABASE}
           MYSQL_USER: ${MYSQL_USER}
           MYSQL_PASSWORD: ${MYSQL_PASSWORD}
           MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./docker/dice-mariadb:/var/lib/mysql
        healthcheck:
          interval: 10s
          retries: 5
          test:
            [
              "CMD",
              "healthcheck.sh",
              "--su-mysql",
              "--connect",
              "--innodb_initialized"
            ]
          timeout: 30s
        networks:
            - dice-db-network

networks:
    dice-db-network:
