FROM nginx:latest

RUN apt-get update && apt-get install -y bash
RUN apt-get install -y iproute2 nano

RUN apt-get install -y npm iputils-ping

RUN apt-get install -y rsyslog

RUN apt-get install -y npm

COPY ./docker/config/nginx/nginx.conf /etc/nginx/conf.d/default.conf
