FROM nginx:latest

RUN apt-get update && apt-get install -y bash
RUN apt-get install -y iproute2 nano

RUN apt-get install -y npm iputils-ping

RUN apt-get install -y rsyslog

#Install Last Version Of Node/NPM
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
RUN apt update
RUN apt install -y nodejs

COPY ./docker/config/nginx/nginx.conf /etc/nginx/conf.d/default.conf
