FROM nginx:latest

RUN apt-get update && apt-get install -y bash
RUN apt-get install -y iproute2 nano

RUN apt-get install -y npm iputils-ping

RUN apt-get install -y rsyslog

#Install Last Version Of Node/NPM
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
RUN apt update
RUN apt install -y nodejs

#For Vitest Browser Support with PlayWright:
#RUN apt-get install libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxdamage1 libxkbcommon0 libpango-1.0-0 libcairo2 libasound2 libatspi2.0-0  libgtk-3.so.0 libgdk-3.so.0 libpangocairo-1.0.so.0 libcairo-gobject.so.2
#RUN npx playwright install-deps
RUN npm install playwright@1.47.2
RUN npx playwright install

COPY ./docker/config/nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html/
